name: Update GitHub Contributions Graph

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate 3D Contribution Graph
        run: |
          mkdir -p profile-3d-contrib
          curl -o profile-3d-contrib/profile-green-animate.svg https://github.com/humayun-raza-030/humayun-raza-030/raw/main/profile-3d-contrib/profile-green-animate.svg

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add profile-3d-contrib/profile-green-animate.svg
          git commit -m "Updated 3D Contribution Graph" || echo "No changes to commit"
          git push origin main
